In [67]:
import numpy as np
import pandas as pd
import re
import random
from bs4 import BeautifulSoup as bs
import requests
import datetime

In [10]:
start_date = datetime.date(1981, 1, 1)
end_date = datetime.date(2003, 12, 31)

def generate_date(start_date,end_date):
    time_between_dates = end_date - start_date
    days_between_dates = time_between_dates.days
    random_number_of_days = random.randrange(days_between_dates)
    random_date = start_date + datetime.timedelta(days=random_number_of_days)
    return random_date

## age considered here is 18 - 40

In [14]:
date = generate_date(start_date,end_date)

In [15]:
date

datetime.date(2000, 6, 22)

In [16]:
Dob_list = []
for i in range(1387):
    date_ = generate_date(start_date,end_date)
    Dob_list.append(date_)

In [17]:
Dob_list

[datetime.date(1982, 3, 31),
 datetime.date(1994, 6, 9),
 datetime.date(1999, 2, 7),
 datetime.date(1987, 7, 1),
 datetime.date(1988, 1, 28),
 datetime.date(1998, 8, 28),
 datetime.date(2000, 11, 13),
 datetime.date(1999, 5, 31),
 datetime.date(1988, 12, 31),
 datetime.date(1995, 8, 12),
 datetime.date(1993, 10, 29),
 datetime.date(2003, 10, 11),
 datetime.date(1997, 8, 30),
 datetime.date(1995, 5, 27),
 datetime.date(1990, 2, 13),
 datetime.date(1997, 3, 28),
 datetime.date(1996, 9, 15),
 datetime.date(2001, 1, 1),
 datetime.date(2001, 11, 25),
 datetime.date(2002, 12, 5),
 datetime.date(1998, 5, 12),
 datetime.date(1985, 4, 26),
 datetime.date(1993, 2, 1),
 datetime.date(1986, 2, 11),
 datetime.date(1989, 8, 20),
 datetime.date(1992, 2, 16),
 datetime.date(1994, 3, 16),
 datetime.date(1991, 9, 7),
 datetime.date(1983, 7, 19),
 datetime.date(1982, 1, 12),
 datetime.date(1989, 12, 28),
 datetime.date(1992, 3, 10),
 datetime.date(1981, 6, 18),
 datetime.date(1999, 12, 22),
 datetime.date(1993, 1, 6),
 datetime.date(1982, 2, 17),
 datetime.date(1984, 7, 23),
 datetime.date(1981, 8, 10),
 datetime.date(1983, 11, 25),
 datetime.date(1986, 7, 22),
 datetime.date(1989, 7, 12),
 datetime.date(1992, 5, 12),
 datetime.date(1996, 3, 26),
 datetime.date(2003, 1, 11),
 datetime.date(1998, 5, 20),
 datetime.date(1984, 6, 14),
 datetime.date(1999, 6, 10),
 datetime.date(1982, 12, 22),
 datetime.date(1986, 11, 15),
 datetime.date(1982, 2, 19),
 datetime.date(1993, 7, 18),
 datetime.date(1998, 10, 9),
 datetime.date(2003, 2, 22),
 datetime.date(1998, 4, 19),
 datetime.date(1981, 3, 4),
 datetime.date(1982, 1, 2),
 datetime.date(2001, 4, 23),
 datetime.date(1986, 7, 5),
 datetime.date(1981, 1, 22),
 datetime.date(1992, 1, 22),
 datetime.date(1991, 12, 3),
 datetime.date(1983, 12, 9),
 datetime.date(1997, 12, 23),
 datetime.date(1989, 10, 11),
 datetime.date(1981, 10, 10),
 datetime.date(2003, 9, 14),
 datetime.date(1989, 11, 4),
 datetime.date(1991, 5, 13),
 datetime.date(1994, 5, 26),
 datetime.date(1990, 3, 13),
 datetime.date(1996, 7, 1),
 datetime.date(2000, 2, 2),
 datetime.date(1989, 4, 2),
 datetime.date(1998, 9, 15),
 datetime.date(1986, 11, 28),
 datetime.date(1982, 7, 12),
 datetime.date(1988, 10, 27),
 datetime.date(1984, 12, 12),
 datetime.date(1991, 3, 16),
 datetime.date(1992, 5, 26),
 datetime.date(1990, 7, 25),
 datetime.date(1982, 2, 19),
 datetime.date(1989, 7, 23),
 datetime.date(2002, 11, 18),
 datetime.date(1990, 4, 9),
 datetime.date(1986, 8, 26),
 datetime.date(1985, 11, 9),
 datetime.date(1989, 10, 19),
 datetime.date(1982, 2, 1),
 datetime.date(1999, 5, 15),
 datetime.date(1997, 5, 3),
 datetime.date(2003, 8, 11),
 datetime.date(1995, 11, 18),
 datetime.date(1998, 10, 22),
 datetime.date(1998, 12, 8),
 datetime.date(1995, 3, 20),
 datetime.date(1998, 11, 18),
 datetime.date(1983, 7, 22),
 datetime.date(1999, 5, 15),
 datetime.date(1985, 2, 20),
 datetime.date(1994, 8, 27),
 datetime.date(1981, 11, 16),
 datetime.date(1993, 8, 17),
 datetime.date(1991, 5, 5),
 datetime.date(1994, 2, 24),
 datetime.date(1983, 3, 11),
 datetime.date(1989, 5, 2),
 datetime.date(1985, 12, 13),
 datetime.date(1988, 9, 3),
 datetime.date(1988, 7, 18),
 datetime.date(1990, 6, 19),
 datetime.date(1989, 12, 18),
 datetime.date(1982, 12, 24),
 datetime.date(1997, 9, 3),
 datetime.date(1996, 8, 12),
 datetime.date(1996, 11, 12),
 datetime.date(1993, 12, 30),
 datetime.date(1989, 4, 28),
 datetime.date(2003, 2, 17),
 datetime.date(1982, 7, 1),
 datetime.date(1993, 1, 29),
 datetime.date(1983, 10, 20),
 datetime.date(1998, 11, 6),
 datetime.date(1992, 8, 7),
 datetime.date(1981, 11, 2),
 datetime.date(2000, 7, 27),
 datetime.date(1996, 1, 26),
 datetime.date(2002, 12, 25),
 datetime.date(1987, 1, 2),
 datetime.date(1992, 9, 27),
 datetime.date(1988, 8, 7),
 datetime.date(1986, 11, 18),
 datetime.date(1993, 4, 20),
 datetime.date(1988, 10, 24),
 datetime.date(2003, 1, 31),
 datetime.date(1990, 12, 4),
 datetime.date(1995, 4, 13),
 datetime.date(1988, 7, 24),
 datetime.date(1982, 3, 1),
 datetime.date(1992, 8, 25),
 datetime.date(1992, 7, 3),
 datetime.date(1994, 3, 23),
 datetime.date(1997, 10, 26),
 datetime.date(1993, 4, 3),
 datetime.date(1981, 1, 22),
 datetime.date(1999, 7, 20),
 datetime.date(1982, 1, 21),
 datetime.date(2001, 7, 16),
 datetime.date(2002, 1, 15),
 datetime.date(1988, 9, 18),
 datetime.date(1986, 5, 6),
 datetime.date(1985, 12, 16),
 datetime.date(1990, 6, 22),
 datetime.date(1998, 7, 30),
 datetime.date(1991, 3, 1),
 datetime.date(2003, 9, 29),
 datetime.date(2000, 8, 6),
 datetime.date(1995, 4, 11),
 datetime.date(2000, 11, 27),
 datetime.date(1996, 12, 21),
 datetime.date(1983, 10, 19),
 datetime.date(1988, 12, 20),
 datetime.date(2000, 8, 31),
 datetime.date(2002, 10, 22),
 datetime.date(2000, 1, 27),
 datetime.date(1990, 10, 31),
 datetime.date(1996, 2, 28),
 datetime.date(2003, 11, 24),
 datetime.date(1989, 7, 2),
 datetime.date(2001, 2, 22),
 datetime.date(1992, 8, 24),
 datetime.date(1995, 8, 22),
 datetime.date(1988, 4, 7),
 datetime.date(1997, 9, 2),
 datetime.date(1984, 11, 9),
 datetime.date(2003, 9, 21),
 datetime.date(2001, 7, 21),
 datetime.date(2003, 6, 14),
 datetime.date(1990, 8, 7),
 datetime.date(1983, 11, 10),
 datetime.date(1983, 6, 20),
 datetime.date(1996, 11, 28),
 datetime.date(1985, 8, 14),
 datetime.date(1986, 4, 23),
 datetime.date(1989, 8, 25),
 datetime.date(2002, 4, 9),
 datetime.date(1999, 10, 29),
 datetime.date(1997, 8, 10),
 datetime.date(1986, 12, 31),
 datetime.date(2001, 9, 13),
 datetime.date(1988, 3, 27),
 datetime.date(1987, 9, 11),
 datetime.date(1993, 8, 9),
 datetime.date(2001, 10, 11),
 datetime.date(1995, 10, 24),
 datetime.date(1994, 2, 27),
 datetime.date(2002, 5, 5),
 datetime.date(1987, 3, 28),
 datetime.date(1993, 7, 19),
 datetime.date(1982, 8, 18),
 datetime.date(1986, 10, 21),
 datetime.date(2002, 12, 18),
 datetime.date(2003, 12, 20),
 datetime.date(1985, 12, 10),
 datetime.date(1991, 9, 27),
 datetime.date(1981, 11, 1),
 datetime.date(1993, 8, 23),
 datetime.date(2002, 11, 25),
 datetime.date(1984, 12, 21),
 datetime.date(1981, 9, 1),
 datetime.date(2001, 2, 3),
 datetime.date(1989, 8, 2),
 datetime.date(1991, 7, 29),
 datetime.date(1996, 11, 2),
 datetime.date(1983, 3, 6),
 datetime.date(1998, 3, 28),
 datetime.date(1988, 1, 30),
 datetime.date(1987, 1, 11),
 datetime.date(1982, 6, 22),
 datetime.date(1982, 8, 21),
 datetime.date(2000, 4, 26),
 datetime.date(1987, 9, 25),
 datetime.date(1999, 2, 6),
 datetime.date(1984, 4, 16),
 datetime.date(1990, 7, 3),
 datetime.date(2003, 8, 26),
 datetime.date(1983, 12, 30),
 datetime.date(1991, 10, 13),
 datetime.date(1994, 7, 2),
 datetime.date(1982, 4, 15),
 datetime.date(1989, 11, 22),
 datetime.date(1989, 4, 19),
 datetime.date(2000, 9, 17),
 datetime.date(1988, 6, 21),
 datetime.date(1993, 1, 19),
 datetime.date(1983, 8, 31),
 datetime.date(1997, 2, 16),
 datetime.date(1995, 6, 24),
 datetime.date(1985, 8, 15),
 datetime.date(2001, 8, 9),
 datetime.date(1996, 12, 6),
 datetime.date(1989, 12, 12),
 datetime.date(1989, 7, 25),
 datetime.date(1995, 5, 20),
 datetime.date(1992, 11, 17),
 datetime.date(1994, 5, 12),
 datetime.date(2002, 2, 11),
 datetime.date(1993, 12, 27),
 datetime.date(1995, 1, 20),
 datetime.date(1981, 9, 28),
 datetime.date(1982, 5, 17),
 datetime.date(1991, 3, 6),
 datetime.date(1989, 2, 27),
 datetime.date(1992, 11, 21),
 datetime.date(1982, 2, 14),
 datetime.date(1990, 8, 4),
 datetime.date(2002, 9, 17),
 datetime.date(2000, 2, 20),
 datetime.date(2001, 12, 21),
 datetime.date(1981, 11, 16),
 datetime.date(1992, 1, 25),
 datetime.date(1987, 10, 8),
 datetime.date(1996, 2, 8),
 datetime.date(2002, 2, 22),
 datetime.date(1993, 10, 4),
 datetime.date(1990, 8, 28),
 datetime.date(1996, 5, 21),
 datetime.date(2003, 12, 17),
 datetime.date(1982, 11, 30),
 datetime.date(1996, 8, 25),
 datetime.date(1995, 2, 17),
 datetime.date(1995, 11, 18),
 datetime.date(1991, 8, 24),
 datetime.date(2001, 9, 13),
 datetime.date(2003, 3, 6),
 datetime.date(1999, 12, 24),
 datetime.date(1992, 7, 11),
 datetime.date(1998, 10, 4),
 datetime.date(1998, 6, 29),
 datetime.date(2002, 11, 8),
 datetime.date(1981, 11, 3),
 datetime.date(1981, 4, 13),
 datetime.date(2002, 6, 18),
 datetime.date(1981, 8, 26),
 datetime.date(1981, 8, 14),
 datetime.date(1993, 9, 27),
 datetime.date(1997, 12, 17),
 datetime.date(1995, 9, 5),
 datetime.date(1987, 1, 22),
 datetime.date(1999, 9, 3),
 datetime.date(1984, 7, 21),
 datetime.date(1993, 2, 19),
 datetime.date(1986, 2, 12),
 datetime.date(2002, 10, 27),
 datetime.date(1986, 5, 29),
 datetime.date(1999, 3, 28),
 datetime.date(1983, 4, 20),
 datetime.date(1999, 9, 23),
 datetime.date(1994, 1, 31),
 datetime.date(1989, 5, 26),
 datetime.date(1984, 10, 11),
 datetime.date(2000, 9, 17),
 datetime.date(1991, 12, 8),
 datetime.date(1984, 10, 9),
 datetime.date(1998, 7, 24),
 datetime.date(1992, 7, 20),
 datetime.date(1996, 1, 11),
 datetime.date(1990, 1, 14),
 datetime.date(1988, 11, 6),
 datetime.date(1983, 4, 9),
 datetime.date(1985, 12, 15),
 datetime.date(1984, 7, 20),
 datetime.date(1992, 8, 23),
 datetime.date(1987, 8, 24),
 datetime.date(1986, 3, 14),
 datetime.date(1988, 1, 27),
 datetime.date(1998, 9, 26),
 datetime.date(1982, 5, 7),
 datetime.date(1995, 10, 4),
 datetime.date(1993, 6, 29),
 datetime.date(1993, 12, 26),
 datetime.date(1982, 3, 28),
 datetime.date(1982, 7, 26),
 datetime.date(1993, 11, 26),
 datetime.date(1998, 4, 16),
 datetime.date(1991, 10, 11),
 datetime.date(1982, 12, 18),
 datetime.date(1988, 11, 9),
 datetime.date(1987, 9, 26),
 datetime.date(1984, 8, 17),
 datetime.date(1997, 3, 24),
 datetime.date(2003, 11, 29),
 datetime.date(1985, 2, 13),
 datetime.date(1984, 9, 20),
 datetime.date(1985, 6, 11),
 datetime.date(1987, 4, 8),
 datetime.date(1982, 9, 8),
 datetime.date(1990, 7, 28),
 datetime.date(1995, 11, 5),
 datetime.date(1999, 2, 21),
 datetime.date(1991, 3, 2),
 datetime.date(2002, 1, 28),
 datetime.date(1987, 1, 16),
 datetime.date(1989, 11, 28),
 datetime.date(1983, 8, 6),
 datetime.date(1998, 11, 6),
 datetime.date(1992, 9, 25),
 datetime.date(1995, 9, 15),
 datetime.date(1982, 3, 6),
 datetime.date(1993, 1, 22),
 datetime.date(1998, 4, 27),
 datetime.date(1998, 6, 30),
 datetime.date(1997, 3, 18),
 datetime.date(1982, 4, 5),
 datetime.date(1992, 11, 14),
 datetime.date(2001, 10, 14),
 datetime.date(1998, 11, 1),
 datetime.date(1984, 11, 17),
 datetime.date(1995, 6, 23),
 datetime.date(1988, 9, 22),
 datetime.date(1987, 1, 14),
 datetime.date(1986, 8, 22),
 datetime.date(1988, 9, 15),
 datetime.date(1981, 5, 24),
 datetime.date(1989, 11, 18),
 datetime.date(1983, 10, 25),
 datetime.date(2002, 9, 16),
 datetime.date(2000, 8, 31),
 datetime.date(2002, 11, 27),
 datetime.date(1989, 11, 18),
 datetime.date(1995, 10, 6),
 datetime.date(2002, 7, 31),
 datetime.date(1992, 9, 9),
 datetime.date(1988, 6, 7),
 datetime.date(1987, 6, 29),
 datetime.date(1983, 4, 5),
 datetime.date(1985, 3, 7),
 datetime.date(2000, 10, 17),
 datetime.date(1999, 5, 24),
 datetime.date(1982, 2, 27),
 datetime.date(1993, 6, 21),
 datetime.date(1991, 5, 4),
 datetime.date(2002, 3, 27),
 datetime.date(1990, 8, 12),
 datetime.date(1995, 2, 15),
 datetime.date(1985, 10, 27),
 datetime.date(1990, 1, 7),
 datetime.date(1995, 10, 21),
 datetime.date(1990, 3, 28),
 datetime.date(1997, 5, 16),
 datetime.date(1996, 10, 4),
 datetime.date(1984, 10, 6),
 datetime.date(1986, 9, 15),
 datetime.date(1981, 8, 31),
 datetime.date(1982, 1, 31),
 datetime.date(1985, 2, 23),
 datetime.date(2003, 2, 26),
 datetime.date(1983, 12, 16),
 datetime.date(1992, 7, 30),
 datetime.date(1998, 2, 10),
 datetime.date(1987, 3, 13),
 datetime.date(1982, 2, 27),
 datetime.date(1998, 9, 15),
 datetime.date(1998, 3, 25),
 datetime.date(2003, 12, 12),
 datetime.date(1984, 1, 31),
 datetime.date(1982, 1, 16),
 datetime.date(1998, 1, 7),
 datetime.date(2002, 2, 6),
 datetime.date(1991, 5, 12),
 datetime.date(2001, 1, 10),
 datetime.date(1998, 6, 6),
 datetime.date(1989, 12, 1),
 datetime.date(1987, 3, 13),
 datetime.date(2001, 1, 24),
 datetime.date(1991, 5, 9),
 datetime.date(2000, 7, 23),
 datetime.date(1987, 1, 17),
 datetime.date(2003, 12, 6),
 datetime.date(1997, 6, 29),
 datetime.date(1998, 8, 21),
 datetime.date(1985, 6, 3),
 datetime.date(1986, 6, 30),
 datetime.date(1992, 5, 28),
 datetime.date(1985, 3, 25),
 datetime.date(1989, 11, 4),
 datetime.date(1997, 1, 1),
 datetime.date(2002, 5, 8),
 datetime.date(1984, 10, 5),
 datetime.date(2003, 5, 27),
 datetime.date(1984, 8, 4),
 datetime.date(2000, 9, 7),
 datetime.date(2002, 12, 23),
 datetime.date(2002, 11, 30),
 datetime.date(1997, 11, 4),
 datetime.date(1995, 3, 9),
 datetime.date(2001, 8, 10),
 datetime.date(1987, 4, 3),
 datetime.date(1997, 7, 19),
 datetime.date(1989, 4, 23),
 datetime.date(1985, 9, 26),
 datetime.date(1987, 8, 22),
 datetime.date(1988, 2, 2),
 datetime.date(1992, 4, 17),
 datetime.date(1998, 1, 20),
 datetime.date(1999, 7, 5),
 datetime.date(1981, 7, 14),
 datetime.date(1983, 12, 29),
 datetime.date(1981, 11, 19),
 datetime.date(1986, 7, 4),
 datetime.date(1981, 3, 19),
 datetime.date(1983, 9, 9),
 datetime.date(1996, 11, 17),
 datetime.date(1993, 10, 28),
 datetime.date(1992, 8, 11),
 datetime.date(1987, 2, 7),
 datetime.date(2002, 12, 12),
 datetime.date(2003, 11, 30),
 datetime.date(1991, 10, 21),
 datetime.date(2000, 9, 11),
 datetime.date(1996, 6, 26),
 datetime.date(1994, 10, 26),
 datetime.date(2000, 12, 14),
 datetime.date(1998, 9, 13),
 datetime.date(1982, 9, 12),
 datetime.date(1990, 12, 28),
 datetime.date(1981, 5, 10),
 datetime.date(1998, 12, 11),
 datetime.date(2002, 6, 21),
 datetime.date(1986, 10, 31),
 datetime.date(1987, 9, 9),
 datetime.date(1993, 11, 6),
 datetime.date(1994, 8, 10),
 datetime.date(1989, 3, 24),
 datetime.date(1989, 9, 27),
 datetime.date(1985, 9, 19),
 datetime.date(1982, 9, 23),
 datetime.date(1997, 5, 25),
 datetime.date(1989, 12, 21),
 datetime.date(1987, 4, 26),
 datetime.date(1985, 11, 20),
 datetime.date(1995, 12, 16),
 datetime.date(2003, 6, 28),
 datetime.date(2001, 4, 23),
 datetime.date(1992, 3, 2),
 datetime.date(1983, 1, 6),
 datetime.date(1998, 11, 12),
 datetime.date(1996, 1, 7),
 datetime.date(1997, 1, 31),
 datetime.date(2000, 7, 12),
 datetime.date(1996, 8, 20),
 datetime.date(1992, 3, 4),
 datetime.date(2000, 12, 17),
 datetime.date(1992, 8, 10),
 datetime.date(1987, 3, 10),
 datetime.date(1996, 9, 28),
 datetime.date(1988, 6, 24),
 datetime.date(2000, 11, 27),
 datetime.date(1989, 6, 23),
 datetime.date(1984, 9, 23),
 datetime.date(1983, 10, 7),
 datetime.date(1983, 7, 13),
 datetime.date(1990, 12, 29),
 datetime.date(1982, 9, 6),
 datetime.date(1996, 8, 11),
 datetime.date(1988, 8, 21),
 datetime.date(1981, 7, 17),
 datetime.date(1985, 9, 14),
 datetime.date(1982, 11, 28),
 datetime.date(2002, 7, 27),
 datetime.date(1991, 5, 24),
 datetime.date(1986, 9, 20),
 datetime.date(1997, 3, 21),
 datetime.date(1994, 1, 17),
 datetime.date(1983, 9, 5),
 datetime.date(1997, 2, 18),
 datetime.date(1991, 4, 13),
 datetime.date(1986, 10, 22),
 datetime.date(1983, 3, 1),
 datetime.date(1992, 3, 24),
 datetime.date(1995, 12, 19),
 datetime.date(1991, 1, 11),
 datetime.date(2002, 10, 19),
 datetime.date(2000, 5, 15),
 datetime.date(1992, 4, 10),
 datetime.date(1992, 5, 27),
 datetime.date(1984, 4, 26),
 datetime.date(2000, 8, 22),
 datetime.date(1996, 10, 21),
 datetime.date(1992, 12, 10),
 datetime.date(1994, 5, 7),
 datetime.date(1986, 9, 12),
 datetime.date(1983, 7, 11),
 datetime.date(1997, 12, 1),
 datetime.date(1995, 9, 10),
 datetime.date(1986, 3, 15),
 datetime.date(1999, 7, 9),
 datetime.date(1992, 12, 10),
 datetime.date(1991, 4, 22),
 datetime.date(1994, 5, 16),
 datetime.date(1986, 3, 19),
 datetime.date(1988, 11, 18),
 datetime.date(1998, 10, 29),
 datetime.date(1989, 5, 11),
 datetime.date(1990, 7, 8),
 datetime.date(1991, 10, 28),
 datetime.date(1997, 1, 26),
 datetime.date(1989, 7, 21),
 datetime.date(1998, 3, 7),
 datetime.date(1994, 10, 26),
 datetime.date(1987, 5, 20),
 datetime.date(1985, 7, 11),
 datetime.date(1995, 10, 3),
 datetime.date(2002, 4, 8),
 datetime.date(1999, 8, 4),
 datetime.date(1997, 1, 16),
 datetime.date(1998, 4, 9),
 datetime.date(1996, 10, 22),
 datetime.date(2002, 3, 31),
 datetime.date(1996, 11, 12),
 datetime.date(2000, 2, 21),
 datetime.date(1989, 3, 6),
 datetime.date(2000, 7, 11),
 datetime.date(1983, 2, 20),
 datetime.date(1983, 12, 17),
 datetime.date(2003, 6, 11),
 datetime.date(1995, 9, 11),
 datetime.date(1986, 10, 17),
 datetime.date(1996, 2, 28),
 datetime.date(1996, 3, 8),
 datetime.date(1996, 11, 23),
 datetime.date(1983, 3, 1),
 datetime.date(1981, 5, 9),
 datetime.date(2000, 10, 1),
 datetime.date(2002, 2, 15),
 datetime.date(1992, 9, 7),
 datetime.date(1995, 2, 6),
 datetime.date(1999, 1, 10),
 datetime.date(1994, 1, 16),
 datetime.date(1997, 1, 13),
 datetime.date(2000, 2, 10),
 datetime.date(1985, 2, 1),
 datetime.date(1984, 2, 18),
 datetime.date(1991, 10, 3),
 datetime.date(1983, 9, 26),
 datetime.date(1997, 1, 14),
 datetime.date(1982, 10, 25),
 datetime.date(2001, 6, 8),
 datetime.date(1985, 3, 8),
 datetime.date(1988, 2, 20),
 datetime.date(1993, 1, 4),
 datetime.date(1987, 6, 25),
 datetime.date(1983, 8, 11),
 datetime.date(1988, 12, 8),
 datetime.date(1984, 7, 5),
 datetime.date(1990, 5, 9),
 datetime.date(1983, 10, 16),
 datetime.date(1986, 4, 2),
 datetime.date(1989, 8, 31),
 datetime.date(1993, 3, 28),
 datetime.date(1998, 9, 22),
 datetime.date(1989, 5, 19),
 datetime.date(1987, 5, 21),
 datetime.date(2001, 3, 27),
 datetime.date(1981, 8, 11),
 datetime.date(1983, 10, 8),
 datetime.date(1999, 11, 24),
 datetime.date(1981, 12, 9),
 datetime.date(1989, 3, 21),
 datetime.date(1991, 6, 13),
 datetime.date(1999, 4, 6),
 datetime.date(1991, 7, 15),
 datetime.date(1996, 1, 27),
 datetime.date(2003, 4, 20),
 datetime.date(1997, 1, 19),
 datetime.date(1999, 4, 17),
 datetime.date(1981, 2, 7),
 datetime.date(1996, 10, 20),
 datetime.date(1981, 1, 7),
 datetime.date(2003, 1, 13),
 datetime.date(1982, 12, 8),
 datetime.date(1997, 5, 27),
 datetime.date(1988, 6, 13),
 datetime.date(1991, 6, 13),
 datetime.date(2003, 9, 11),
 datetime.date(1986, 10, 22),
 datetime.date(2000, 8, 8),
 datetime.date(1987, 9, 11),
 datetime.date(2002, 12, 24),
 datetime.date(1992, 3, 19),
 datetime.date(1984, 12, 12),
 datetime.date(1981, 5, 21),
 datetime.date(1989, 1, 20),
 datetime.date(2000, 3, 25),
 datetime.date(1981, 6, 24),
 datetime.date(1995, 2, 1),
 datetime.date(2001, 12, 24),
 datetime.date(1993, 2, 16),
 datetime.date(1984, 11, 9),
 datetime.date(1990, 4, 2),
 datetime.date(1999, 4, 8),
 datetime.date(2002, 1, 8),
 datetime.date(2000, 10, 29),
 datetime.date(1992, 8, 21),
 datetime.date(1992, 6, 11),
 datetime.date(1994, 3, 3),
 datetime.date(1990, 10, 1),
 datetime.date(1985, 2, 4),
 datetime.date(1987, 10, 25),
 datetime.date(2000, 12, 6),
 datetime.date(1981, 4, 22),
 datetime.date(1999, 10, 5),
 datetime.date(2000, 5, 31),
 datetime.date(1982, 10, 3),
 datetime.date(1993, 8, 5),
 datetime.date(1988, 11, 6),
 datetime.date(1996, 1, 20),
 datetime.date(1987, 12, 31),
 datetime.date(1990, 10, 17),
 datetime.date(1989, 12, 22),
 datetime.date(1983, 10, 6),
 datetime.date(1982, 4, 2),
 datetime.date(2002, 6, 21),
 datetime.date(1989, 9, 10),
 datetime.date(1982, 2, 26),
 datetime.date(1993, 1, 25),
 datetime.date(2002, 8, 26),
 datetime.date(1985, 4, 26),
 datetime.date(1997, 10, 11),
 datetime.date(1984, 9, 1),
 datetime.date(1987, 4, 14),
 datetime.date(1991, 12, 17),
 datetime.date(1984, 9, 14),
 datetime.date(1991, 5, 16),
 datetime.date(2000, 2, 15),
 datetime.date(1989, 3, 19),
 datetime.date(1993, 6, 23),
 datetime.date(1993, 9, 11),
 datetime.date(1990, 3, 30),
 datetime.date(2002, 6, 7),
 datetime.date(1994, 2, 1),
 datetime.date(2000, 8, 1),
 datetime.date(1990, 3, 4),
 datetime.date(2003, 5, 15),
 datetime.date(2001, 5, 25),
 datetime.date(1994, 8, 24),
 datetime.date(1997, 3, 22),
 datetime.date(2002, 6, 20),
 datetime.date(1985, 3, 12),

## Recaliing Data frame from DP1

In [20]:
df = pd.read_csv('Name Sheet With Gender',index_col=[0])

In [21]:
df.loc[:,'DOB'] = Dob_list
df

                  Name  Gender         DOB
0           Amoli Veer  Female  1982-03-31
1     Kaia Subramanian  Female  1994-06-09
2          Rushil Vish    Male  1999-02-07
3       Atiksh Manohar    Male  1987-07-01
4           Ved Kapoor    Male  1988-01-28
...                ...     ...         ...
1382         Neysa Rai  Female  1989-12-10
1383     Raunak Kapoor    Male  1984-08-12
1384        Taara Veer  Female  1995-06-06
1385       Sarthak Rai    Male  1997-09-03
1386      Kairav Dutta    Male  1999-11-06

[1387 rows x 3 columns]

In [23]:
df.to_csv("Name Sheet With Gender.csv")

In [1]:
from bs4 import BeautifulSoup as bs
import requests

In [2]:
def parse_url(url):
    page  = requests.get(url).text
    return bs(page)

In [4]:
city = parse_url('http://www.getpincodes.com/pincodes-of-pune-city-taluk-pune-district-maharashtra')

In [17]:
city.find('table').find_all('tr')[1]

<tr><td class="text-center">1</td><td><h3 class="h6"><a href="http://www.getpincodes.com/postoffice/9-drd-bo-411014" title="9 DRD B.O">9 DRD B.O</a></h3></td><td class="text-center">Pune City</td><td class="text-center">Pune</td><td class="h6 text-center"><a href="http://www.getpincodes.com/pincode/411014" title="411014">411014</a></td></tr>

In [15]:
city.find('table').find_all('tr')[1].find('a').text

'9 DRD B.O'

In [58]:
city.find('table').find_all('tr')[1].find('td' , class_ = 'h6').text

'411014'

In [62]:
Name = city.find('table').find_all('tr')
Pincodes = city.find('table').find_all('tr')

In [81]:
len(Name)

130

In [85]:
locations_dict = {(Name[i].find('a').text):(Pincodes[i].find('td' , class_ = 'h6').text) for i in range(1,130)}

In [86]:
locations_dict

{'9 DRD B.O': '411014',
 'AFMC S.O': '411040',
 'Airport S.O (Pune)': '411032',
 'Akurdi S.O': '411035',
 'Ammunition Factory Khadki S.O': '411003',
 'Bhosari I.E. S.O': '411026',
 'Bhosarigoan S.O': '411039',
 'Bibvewadi S.O': '411037',
 'C D A (O) S.O': '411001',
 'C M E S.O': '411031',
 'Chinchwad East S.O': '411019',
 'Chinchwadgaon S.O': '411033',
 'Dapodi Bazar S.O': '411012',
 'Dapodi S.O': '411012',
 'Dhanori B.O': '411015',
 'Dighi Camp S.O': '411015',
 'Dr.B.A. Chowk S.O': '411001',
 'Dukirkline S.O': '411014',
 'East Khadki S.O': '411003',
 'Ghorpuri Bazar S.O': '411001',
 'H.E. Factory S.O': '411003',
 'Hadapsar S.O': '411028',
 'Hadpsar I.E. S.O': '411013',
 'Iaf Station S.O': '411032',
 'Indrayaninagar S.O': '411026',
 'Kalewadi B.O': '411017',
 'Kasarwadi S.O': '411034',
 'Khadki Bazar S.O': '411003',
 'Khadki S.O': '411003',
 'Khondhwa KH B.O': '411048',
 'Kondhwa BK B.O': '411048',
 'Kondhwa Lh B.O': '411048',
 'Lohogaon S.O': '411047',
 'M.Phulenagar S.O': '411019',
 'Market Yard S.O (Pune)': '411037',
 'Masulkar Colony S.O': '411018',
 'Mohamadwadi S.O': '411060',
 'Mundhva AV S.O': '411036',
 'Mundhva B.O': '411036',
 'N I B M S.O': '411048',
 'N.W. College S.O': '411001',
 'Nehrunagar S.O (Pune)': '411018',
 'P.C.N.T. S.O': '411044',
 'Pimpri Colony S.O': '411017',
 'Pimpri P F S.O': '411018',
 'Pimpri Waghire S.O': '411017',
 'Punawale B.O': '411033',
 'Pune Cantt East S.O': '411001',
 'Pune H.O': '411001',
 'Pune New Bazar S.O': '411001',
 'Rupeenagar S.O': '412114',
 'Sachapir Street S.O': '411001',
 'Salisbury Park S.O': '411037',
 'Sangavi S.O': '411027',
 'Sasanenagar S.O': '411028',
 'Srpf S.O': '411022',
 'T.V. Nagar S.O': '411037',
 'Talwade B.O': '412114',
 'Thathawade B.O': '411033',
 'Thergaon B.O': '411033',
 'Vadgaon Sheri S.O': '411014',
 'Vidyanagar S.O (Pune)': '411032',
 'Vishrantwadi S.O': '411015',
 'Wakad B.O': '411057',
 'Wanowarie S.O': '411040',
 'Yamunanagar S.O': '411044',
 'Yerwada S.O': '411006',
 'Yerwada T.S. S.O': '411006',
 'A.R. Shala S.O': '411004',
 'Anandnagar S.O (Pune)': '411051',
 'Armament S.O': '411021',
 'Aundh T.S. S.O': '411007',
 'Bajirao Road S.O': '411002',
 'Baner Road S.O': '411007',
 'Bhavani Peth S.O': '411042',
 'Bhusari Colony S.O': '411038',
 'Botanical Garden S.O (Pune)': '411003',
 'Congress House Road S.O': '411005',
 'Deccan Gymkhana S.O': '411004',
 'Dhankawadi S.O': '411043',
 'Ex. Serviceman Colony S.O': '411038',
 'Film Institute S.O': '411004',
 'Ganeshkhind S.O': '411007',
 'Ghorpade Peth S.O': '411042',
 'Govt. Polytechnic S.O': '411016',
 'Guruwar Peth S.O': '411042',
 'Kapad Ganj S.O': '411002',
 'Karvenagar S.O': '411052',
 'Kasba Peth S.O': '411011',
 'Katraj S.O': '411046',
 'Khadakwasla R.S. S.O': '411024',
 'Kothrud S.O': '411038',
 'Lokmanyanagar S.O': '411030',
 'Mangalwar Peth S.O (Pune)': '411011',
 'Model Colony S.O': '411016',
 'N.C.L. Pune S.O': '411008',
 'N.D.A. Khadakwasla S.O': '411023',
 'N.I.A. S.O': '411045',
 'Nana Peth S.O': '411002',
 'Narayan Peth S.O': '411030',
 'Navsahyadri S.O': '411052',
 'Parvati Gaon S.O': '411009',
 'Parvati S.O': '411009',
 'Pune City H.O': '411002',
 'Range Hills S.O': '411020',
 'Rashtra Bhasha Bhavan S.O': '411030',
 'Rasta Peth S.O': '411011',
 'Raviwar Peth S.O': '411002',
 'S.P. College S.O': '411030',
 'S.S.C.Exam Board S.O': '411005',
 'Sadashiv Peth S.O': '411030',
 'Shaniwar Peth S.O (Pune)': '411030',
 'Shivaji Housing Society S.O': '411016',
 'Shivajinagar S.O (Pune)': '411005',
 'Shukrawar Peth S.O (Pune)': '411002',
 'Swargate Chowk S.O': '411042',
 'Swargate S.O': '411042',
 'Vadgaon Budruk S.O': '411041',
 'Warje S.O': '411058',
 'Sub Office Indrayaninagar B.O': '411032',
 'Pune Weather S.O': '411005',
 'Pune R.S. S.O': '411001',
 'Khadki Arsenel S.O': '411003',
 'L.K. Path S.O': '411003',
 'Chinchwadga0n S.O': '411033'}

In [76]:
s = pd.Series(locations_dict, name='Pincode')

In [77]:
s.index.name = 'Name Of Area'

In [78]:
location_df = s.reset_index()

In [79]:
location_df

                      Name Of Area Pincode
0                        9 DRD B.O  411014
1                         AFMC S.O  411040
2               Airport S.O (Pune)  411032
3                       Akurdi S.O  411035
4    Ammunition Factory Khadki S.O  411003
..                             ...     ...
120               Pune Weather S.O  411005
121                  Pune R.S. S.O  411001
122             Khadki Arsenel S.O  411003
123                  L.K. Path S.O  411003
124              Chinchwadga0n S.O  411033

[125 rows x 2 columns]

In [87]:
location_df.shape

(125, 2)

In [89]:
location_df.to_csv('locations.csv')