In [1]:
import numpy as np
import pandas as pd
import re
import random
from bs4 import BeautifulSoup as bs
import requests
import datetime

In [4]:
df = pd.read_csv("Final Dataset before Normalisation.csv", index_col=[0])

In [5]:
df

,Name,Gender,DOB,Name Of Area,Pincode,Latitude,Longitude,Flexibility,Body Composition,Composition Percentage,Interactiveness,Workout Frequency,Workout Mode Preferred,is_sports_enthusiast,like_to_be_mentored,like_to_mentor,fitness_goal_to_be achieved,addons in session,Height_in_cms,Age
0,Amoli Veer,Female,1982-03-31,Nana Peth S.O,411002,18.51009,73.85672,4,Essential Fat,14,4,Only Weekends,Outdoor,No,3,3,All,Meditation,166,39
1,Kaia Subramanian,Female,1994-06-09,Mundhva AV S.O,411036,18.53135,73.91478,5,Fitness,22,5,Alternate Days,Outdoor,Maybe,1,3,Improve endurance/conditioning,Meditation,163,26
2,Rushil Vish,Male,1999-02-07,Yerwada S.O,411006,18.56318,73.87742,3,Acceptable,23,3,Monday To Friday,Both,Yes,4,5,Improve athletic skills,Meditation,171,22
3,Atiksh Manohar,Male,1987-07-01,Dapodi S.O,411012,18.57749,73.83138,5,Athletes,6,3,Alternate Days,Both,Maybe,3,4,Lose fat,Meditation,173,33
4,Ved Kapoor,Male,1988-01-28,Hadapsar S.O,411028,18.50453,73.91255,5,Essential Fat,6,3,3 days of week,Indoor,No,1,1,Build muscle,None,161,33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1382,Neysa Rai,Female,1989-12-10,Mohamadwadi S.O,411060,18.47335,73.90957,2,Fitness,22,4,Any Day of Week,Both,Maybe,2,4,Improve athletic skills,Yoga,170,31
1383,Raunak Kapoor,Male,1984-08-12,Masulkar Colony S.O,411018,18.63374,73.81290,3,Fitness,14,1,Monday To Friday,Outdoor,Yes,2,5,All,None,161,36
1384,Taara Veer,Female,1995-06-06,Masulkar Colony S.O,411018,18.63374,73.81290,5,Fitness,22,1,Only Weekends,Indoor,No,5,4,Build muscle,Both,166,25
1385,Sarthak Rai,Male,1997-09-03,Guruwar Peth S.O,411042,18.50547,73.85951,5,Fitness,14,5,Monday To Friday,Indoor,Maybe,3,2,Improve athletic skills,Yoga,177,23
1386,Kairav Dutta,Male,1999-11-06,Kasarwadi S.O,411034,18.60373,73.82221,1,Athletes,6,1,Daily,Outdoor,Yes,4,2,All,Both,178,21

## Dividing Datasets for Normalisation - Content Filtering

In [25]:
df1 = df[['Name', 'Gender', 'Flexibility', 'Body Composition', 'Composition Percentage', 'Interactiveness', 'Workout Frequency', 'Workout Mode Preferred', 'is_sports_enthusiast', 'like_to_be_mentored', 'like_to_mentor', 'fitness_goal_to_be achieved','addons in session','Height_in_cms','Age']]

In [26]:
df1

,Name,Gender,Flexibility,Body Composition,Composition Percentage,Interactiveness,Workout Frequency,Workout Mode Preferred,is_sports_enthusiast,like_to_be_mentored,like_to_mentor,fitness_goal_to_be achieved,addons in session,Height_in_cms,Age
0,Amoli Veer,Female,4,Essential Fat,14,4,Only Weekends,Outdoor,No,3,3,All,Meditation,166,39
1,Kaia Subramanian,Female,5,Fitness,22,5,Alternate Days,Outdoor,Maybe,1,3,Improve endurance/conditioning,Meditation,163,26
2,Rushil Vish,Male,3,Acceptable,23,3,Monday To Friday,Both,Yes,4,5,Improve athletic skills,Meditation,171,22
3,Atiksh Manohar,Male,5,Athletes,6,3,Alternate Days,Both,Maybe,3,4,Lose fat,Meditation,173,33
4,Ved Kapoor,Male,5,Essential Fat,6,3,3 days of week,Indoor,No,1,1,Build muscle,None,161,33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1382,Neysa Rai,Female,2,Fitness,22,4,Any Day of Week,Both,Maybe,2,4,Improve athletic skills,Yoga,170,31
1383,Raunak Kapoor,Male,3,Fitness,14,1,Monday To Friday,Outdoor,Yes,2,5,All,None,161,36
1384,Taara Veer,Female,5,Fitness,22,1,Only Weekends,Indoor,No,5,4,Build muscle,Both,166,25
1385,Sarthak Rai,Male,5,Fitness,14,5,Monday To Friday,Indoor,Maybe,3,2,Improve athletic skills,Yoga,177,23
1386,Kairav Dutta,Male,1,Athletes,6,1,Daily,Outdoor,Yes,4,2,All,Both,178,21

In [27]:
df1['Gender'] = df1["Gender"].astype('category').cat.codes

<ipython-input-27-9599b35390af>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Gender'] = df1["Gender"].astype('category').cat.codes

In [28]:
df1['Body Composition'] = df1["Body Composition"].astype('category').cat.codes
df1['Workout Frequency'] = df1["Workout Frequency"].astype('category').cat.codes
df1['Workout Mode Preferred'] = df1["Workout Mode Preferred"].astype('category').cat.codes
df1['is_sports_enthusiast'] = df1["is_sports_enthusiast"].astype('category').cat.codes
df1['fitness_goal_to_be achieved'] = df1["fitness_goal_to_be achieved"].astype('category').cat.codes
df1['addons in session'] = df1["addons in session"].astype('category').cat.codes
df1

<ipython-input-28-f42aa0aed271>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Body Composition'] = df1["Body Composition"].astype('category').cat.codes
<ipython-input-28-f42aa0aed271>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Workout Frequency'] = df1["Workout Frequency"].astype('category').cat.codes
<ipython-input-28-f42aa0aed271>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Workout Mode Preferred'] = df1["Workout Mode Preferred"].astype('category').cat.codes
<ipython-input-28-f42aa0aed271>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['is_sports_enthusiast'] = df1["is_sports_enthusiast"].astype('category').cat.codes
<ipython-input-28-f42aa0aed271>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['fitness_goal_to_be achieved'] = df1["fitness_goal_to_be achieved"].astype('category').cat.codes
<ipython-input-28-f42aa0aed271>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['addons in session'] = df1["addons in session"].astype('category').cat.codes

,Name,Gender,Flexibility,Body Composition,Composition Percentage,Interactiveness,Workout Frequency,Workout Mode Preferred,is_sports_enthusiast,like_to_be_mentored,like_to_mentor,fitness_goal_to_be achieved,addons in session,Height_in_cms,Age
0,Amoli Veer,0,4,2,14,4,5,2,1,3,3,0,1,166,39
1,Kaia Subramanian,0,5,3,22,5,1,2,0,1,3,3,1,163,26
2,Rushil Vish,1,3,0,23,3,4,0,2,4,5,2,1,171,22
3,Atiksh Manohar,1,5,1,6,3,1,0,0,3,4,4,1,173,33
4,Ved Kapoor,1,5,2,6,3,0,1,1,1,1,1,2,161,33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1382,Neysa Rai,0,2,3,22,4,2,0,0,2,4,2,3,170,31
1383,Raunak Kapoor,1,3,3,14,1,4,2,2,2,5,0,2,161,36
1384,Taara Veer,0,5,3,22,1,5,1,1,5,4,1,0,166,25
1385,Sarthak Rai,1,5,3,14,5,4,1,0,3,2,2,3,177,23
1386,Kairav Dutta,1,1,1,6,1,3,2,2,4,2,0,0,178,21

In [31]:
df1

,Name,Gender,Flexibility,Body Composition,Composition Percentage,Interactiveness,Workout Frequency,Workout Mode Preferred,is_sports_enthusiast,like_to_be_mentored,like_to_mentor,fitness_goal_to_be achieved,addons in session,Height_in_cms,Age
0,Amoli Veer,0,4,2,14,4,5,2,1,3,3,0,1,166,39
1,Kaia Subramanian,0,5,3,22,5,1,2,0,1,3,3,1,163,26
2,Rushil Vish,1,3,0,23,3,4,0,2,4,5,2,1,171,22
3,Atiksh Manohar,1,5,1,6,3,1,0,0,3,4,4,1,173,33
4,Ved Kapoor,1,5,2,6,3,0,1,1,1,1,1,2,161,33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1382,Neysa Rai,0,2,3,22,4,2,0,0,2,4,2,3,170,31
1383,Raunak Kapoor,1,3,3,14,1,4,2,2,2,5,0,2,161,36
1384,Taara Veer,0,5,3,22,1,5,1,1,5,4,1,0,166,25
1385,Sarthak Rai,1,5,3,14,5,4,1,0,3,2,2,3,177,23
1386,Kairav Dutta,1,1,1,6,1,3,2,2,4,2,0,0,178,21

In [35]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [37]:
df1_scaled = df1.copy() 
names = ['Flexibility','Composition Percentage','Interactiveness', 'like_to_be_mentored', 'like_to_mentor', 'Height_in_cms', 'Age']

df1_scaled[names] = MinMaxScaler().fit_transform(df1_scaled[names])

In [38]:
df1_scaled

,Name,Gender,Flexibility,Body Composition,Composition Percentage,Interactiveness,Workout Frequency,Workout Mode Preferred,is_sports_enthusiast,like_to_be_mentored,like_to_mentor,fitness_goal_to_be achieved,addons in session,Height_in_cms,Age
0,Amoli Veer,0,0.75,2,0.089888,0.75,5,2,1,0.50,0.50,0,1,0.333333,0.956522
1,Kaia Subramanian,0,1.00,3,0.179775,1.00,1,2,0,0.00,0.50,3,1,0.166667,0.391304
2,Rushil Vish,1,0.50,0,0.191011,0.50,4,0,2,0.75,1.00,2,1,0.611111,0.217391
3,Atiksh Manohar,1,1.00,1,0.000000,0.50,1,0,0,0.50,0.75,4,1,0.722222,0.695652
4,Ved Kapoor,1,1.00,2,0.000000,0.50,0,1,1,0.00,0.00,1,2,0.055556,0.695652
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1382,Neysa Rai,0,0.25,3,0.179775,0.75,2,0,0,0.25,0.75,2,3,0.555556,0.608696
1383,Raunak Kapoor,1,0.50,3,0.089888,0.00,4,2,2,0.25,1.00,0,2,0.055556,0.826087
1384,Taara Veer,0,1.00,3,0.179775,0.00,5,1,1,1.00,0.75,1,0,0.333333,0.347826
1385,Sarthak Rai,1,1.00,3,0.089888,1.00,4,1,0,0.50,0.25,2,3,0.944444,0.260870
1386,Kairav Dutta,1,0.00,1,0.000000,0.00,3,2,2,0.75,0.25,0,0,1.000000,0.173913

In [39]:
from sklearn.metrics.pairwise import cosine_similarity

In [41]:
similarity = cosine_similarity(df1_scaled.drop('Name',axis=1))
print(similarity)

[[1.         0.57639427 0.76448018 ... 0.93175764 0.82847777 0.86050866]
 [0.57639427 1.         0.4630589  ... 0.63450653 0.78009334 0.44310995]
 [0.76448018 0.4630589  1.         ... 0.78076512 0.74789524 0.76063691]
 ...
 [0.93175764 0.63450653 0.78076512 ... 1.         0.82155507 0.81345942]
 [0.82847777 0.78009334 0.74789524 ... 0.82155507 1.         0.64975687]
 [0.86050866 0.44310995 0.76063691 ... 0.81345942 0.64975687 1.        ]]

In [43]:
similarity.shape

(1387, 1387)

In [44]:
df1_similarity = pd.DataFrame(similarity, columns=df1_scaled['Name'], index=df1_scaled['Name'])

In [45]:
df1_similarity

Name,Amoli Veer,Kaia Subramanian,Rushil Vish,Atiksh Manohar,Ved Kapoor,Vihaan Chauhan,Tanvi Sandeep,Taara Chauhan,Anaisha Veena,Rebecca Chander,...,Rohan Nagpal,Alisha Roy,Sneha Ranga,Ira Naran,Avni Nath,Neysa Rai,Raunak Kapoor,Taara Veer,Sarthak Rai,Kairav Dutta
Name,,,,,,,,,,,,,,,,,,,,,
Amoli Veer,1.000000,0.576394,0.764480,0.361543,0.475227,0.838377,0.400431,0.641902,0.496552,0.363360,...,0.436871,0.581999,0.834686,0.419573,0.693054,0.648184,0.922759,0.931758,0.828478,0.860509
Kaia Subramanian,0.576394,1.000000,0.463059,0.779831,0.775265,0.787291,0.881068,0.807166,0.856513,0.788548,...,0.435920,0.902143,0.738945,0.589675,0.605648,0.799135,0.625391,0.634507,0.780093,0.443110
Rushil Vish,0.764480,0.463059,1.000000,0.642025,0.400902,0.797938,0.332264,0.788526,0.587194,0.572266,...,0.575465,0.347912,0.848966,0.191324,0.447076,0.600005,0.730301,0.780765,0.747895,0.760637
Atiksh Manohar,0.361543,0.779831,0.642025,1.000000,0.605240,0.683588,0.711144,0.838470,0.796623,0.907875,...,0.600479,0.589385,0.704642,0.280812,0.212113,0.714142,0.394678,0.479873,0.689963,0.293458
Ved Kapoor,0.475227,0.775265,0.400902,0.605240,1.000000,0.598299,0.838187,0.685113,0.847269,0.652608,...,0.650257,0.655934,0.511197,0.622152,0.602323,0.769405,0.685829,0.438665,0.727298,0.426043
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Neysa Rai,0.648184,0.799135,0.600005,0.714142,0.769405,0.818646,0.826608,0.826552,0.859048,0.763268,...,0.726086,0.713655,0.693607,0.587405,0.448602,1.000000,0.732148,0.673992,0.920212,0.417622
Raunak Kapoor,0.922759,0.625391,0.730301,0.394678,0.685829,0.844168,0.542542,0.695867,0.645756,0.421529,...,0.493207,0.635327,0.765647,0.573220,0.808317,0.732148,1.000000,0.872374,0.844751,0.857047
Taara Veer,0.931758,0.634507,0.780765,0.479873,0.438665,0.923005,0.422492,0.666413,0.550836,0.422186,...,0.316390,0.680319,0.830634,0.510417,0.673961,0.673992,0.872374,1.000000,0.821555,0.813459
Sarthak Rai,0.828478,0.780093,0.747895,0.689963,0.727298,0.900807,0.737828,0.832627,0.765941,0.700170,...,0.724788,0.700624,0.829150,0.452655,0.517403,0.920212,0.844751,0.821555,1.000000,0.649757
Kairav Dutta,0.860509,0.443110,0.760637,0.293458,0.426043,0.726383,0.315936,0.556994,0.429149,0.253794,...,0.306389,0.529619,0.763879,0.351365,0.808415,0.417622,0.857047,0.813459,0.649757,1.000000

In [66]:
df1_user=df1_similarity.loc['Raunak Kapoor',:]
df1_user

Name
Amoli Veer          0.922759
Kaia Subramanian    0.625391
Rushil Vish         0.730301
Atiksh Manohar      0.394678
Ved Kapoor          0.685829
                      ...
Neysa Rai           0.732148
Raunak Kapoor       1.000000
Taara Veer          0.872374
Sarthak Rai         0.844751
Kairav Dutta        0.857047
Name: Raunak Kapoor, Length: 1387, dtype: float64

In [83]:
Recommendations=df1_user.sort_values(ascending=False).head()
rec =Recommendations.index.to_list()

In [84]:
df[df.Name.isin(rec)]

,Name,Gender,DOB,Name Of Area,Pincode,Latitude,Longitude,Flexibility,Body Composition,Composition Percentage,Interactiveness,Workout Frequency,Workout Mode Preferred,is_sports_enthusiast,like_to_be_mentored,like_to_mentor,fitness_goal_to_be achieved,addons in session,Height_in_cms,Age
156,Pranay Dhawan,Male,2000-08-06,Mohamadwadi S.O,411060,18.47335,73.90957,4,Fitness,14,4,Only Weekends,Indoor,Yes,3,4,All,None,167,20
814,Taksh Srivastava,Male,1986-11-30,Khondhwa KH B.O,411048,18.45756,73.89339,2,Fitness,14,2,Monday To Friday,Outdoor,Yes,2,1,All,Meditation,176,34
1291,Viti Verma,Female,1983-06-30,Yerwada S.O,411006,18.56318,73.87742,4,Obese,40,1,Monday To Friday,Outdoor,Yes,4,5,All,None,166,37
1346,Neysa Sethi,Female,1982-03-01,Ex. Serviceman Colony S.O,411038,18.48029,73.79853,2,Obese,40,2,Monday To Friday,Outdoor,Yes,3,4,Build muscle,Yoga,166,39
1383,Raunak Kapoor,Male,1984-08-12,Masulkar Colony S.O,411018,18.63374,73.81290,3,Fitness,14,1,Monday To Friday,Outdoor,Yes,2,5,All,None,161,36

In [60]:
df1.Name.isin(['Adah Vish','Amoli Veer'])

0        True
1       False
2       False
3       False
4       False
        ...
1382    False
1383    False
1384    False
1385    False
1386    False
Name: Name, Length: 1387, dtype: bool