In [14]:
import numpy as np
import pandas as pd
import re
import random
from bs4 import BeautifulSoup as bs
import requests
import datetime
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.metrics.pairwise import cosine_similarity, haversine_distances
from math import radians
from sklearn.neighbors import DistanceMetric
global dist 
dist = DistanceMetric.get_metric('haversine')
import ipywidgets as widgets
from IPython.display import display
import warnings
warnings.filterwarnings("ignore")

In [15]:
df = pd.read_csv("Final Dataset before Normalisation.csv", index_col=[0])

## Dividing Datasets

In [16]:
def get_both_datasets_for_normalisation(df):
    df1 = df[['Name', 'Gender', 'Flexibility', 'Pincode', 'Body Composition', 'Composition Percentage', 'Interactiveness', 'Workout Frequency', 'Workout Mode Preferred', 'is_sports_enthusiast', 'like_to_be_mentored', 'like_to_mentor', 'fitness_goal_to_be achieved','addons in session','Height_in_cms','Age']]
    df2 =df[['Name', 'Name Of Area', 'Pincode', 'Latitude ','Longitude']]
    return df1,df2

In [17]:
df1,df2 = get_both_datasets_for_normalisation(df)

In [18]:

def get_df1_normalised(df, names):
    df['Gender'] = df["Gender"].astype('category').cat.codes
    df['Body Composition'] = df["Body Composition"].astype('category').cat.codes
    df['Workout Frequency'] = df["Workout Frequency"].astype('category').cat.codes
    df['Workout Mode Preferred'] = df["Workout Mode Preferred"].astype('category').cat.codes
    df['is_sports_enthusiast'] = df["is_sports_enthusiast"].astype('category').cat.codes
    df['fitness_goal_to_be achieved'] = df["fitness_goal_to_be achieved"].astype('category').cat.codes
    df['addons in session'] = df["addons in session"].astype('category').cat.codes
    df[names] = MinMaxScaler().fit_transform(df[names])
    return df

In [19]:
names = ['Flexibility','Composition Percentage','Pincode', 'Interactiveness', 'like_to_be_mentored', 'like_to_mentor', 'Height_in_cms', 'Age']
df1 = get_df1_normalised(df1,names)

In [20]:
df1

,Name,Gender,Flexibility,Pincode,Body Composition,Composition Percentage,Interactiveness,Workout Frequency,Workout Mode Preferred,is_sports_enthusiast,like_to_be_mentored,like_to_mentor,fitness_goal_to_be achieved,addons in session,Height_in_cms,Age
0,Amoli Veer,0,0.75,0.000898,2,0.12,0.75,5,2,1,0.50,0.50,0,1,0.333333,0.956522
1,Kaia Subramanian,0,1.00,0.031447,3,0.32,1.00,1,2,0,0.00,0.50,3,1,0.166667,0.391304
2,Rushil Vish,1,0.50,0.004492,0,0.32,0.50,4,0,2,0.75,1.00,2,1,0.611111,0.217391
3,Atiksh Manohar,1,1.00,0.009883,1,0.08,0.50,1,0,0,0.50,0.75,4,1,0.722222,0.695652
4,Ved Kapoor,1,1.00,0.024259,2,0.00,0.50,0,1,1,0.00,0.00,1,2,0.055556,0.695652
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1382,Neysa Rai,0,0.25,0.053010,3,0.32,0.75,2,0,0,0.25,0.75,2,3,0.555556,0.608696
1383,Raunak Kapoor,1,0.50,0.015274,3,0.18,0.00,4,2,2,0.25,1.00,0,2,0.055556,0.826087
1384,Taara Veer,0,1.00,0.015274,3,0.32,0.00,5,1,1,1.00,0.75,1,0,0.333333,0.347826
1385,Sarthak Rai,1,1.00,0.036837,3,0.18,1.00,4,1,0,0.50,0.25,2,3,0.944444,0.260870
1386,Kairav Dutta,1,0.00,0.029650,1,0.08,0.00,3,2,2,0.75,0.25,0,0,1.000000,0.173913

In [21]:
df1_scaled = df1.copy()

## Getting Cosine Similarity Matrix

In [22]:
def getSimilarityMatrix(df1_scaled):
    similarity_cos = cosine_similarity(df1_scaled.drop('Name',axis=1))
    df1_similarity = pd.DataFrame(similarity_cos, columns=df1_scaled['Name'], index=df1_scaled['Name'])
    return df1_similarity

In [23]:
df1_similarity_test = getSimilarityMatrix(df1_scaled)

In [24]:
def getUserCorrelation(df1_similarity,name):
    df1_user = df1_similarity.loc[name,:]
    return df1_user

In [25]:
user_corr = getUserCorrelation(df1_similarity_test, 'Amoli Veer')

## Preprocessing for Haversine Distance similarity

In [26]:
def addLatLongRad(df2):
    df2['Latitude_rad'] = np.radians(df2['Latitude '])
    df2['Longitude_rad'] = np.radians(df2['Longitude'])
    return df2

In [27]:
df2 = addLatLongRad(df2)

In [28]:
df2

,Name,Name Of Area,Pincode,Latitude,Longitude,Latitude_rad,Longitude_rad
0,Amoli Veer,Nana Peth S.O,411002,18.51009,73.85672,0.323062,1.289043
1,Kaia Subramanian,Mundhva AV S.O,411036,18.53135,73.91478,0.323433,1.290056
2,Rushil Vish,Yerwada S.O,411006,18.56318,73.87742,0.323989,1.289404
3,Atiksh Manohar,Dapodi S.O,411012,18.57749,73.83138,0.324238,1.288601
4,Ved Kapoor,Hadapsar S.O,411028,18.50453,73.91255,0.322965,1.290017
...,...,...,...,...,...,...,...
1382,Neysa Rai,Mohamadwadi S.O,411060,18.47335,73.90957,0.322421,1.289965
1383,Raunak Kapoor,Masulkar Colony S.O,411018,18.63374,73.81290,0.325220,1.288278
1384,Taara Veer,Masulkar Colony S.O,411018,18.63374,73.81290,0.325220,1.288278
1385,Sarthak Rai,Guruwar Peth S.O,411042,18.50547,73.85951,0.322981,1.289092
1386,Kairav Dutta,Kasarwadi S.O,411034,18.60373,73.82221,0.324696,1.288441

In [29]:
def getDistanceMatrix(df2):
    distance_similarity_df2 = pd.DataFrame(dist.pairwise(df2[['Latitude_rad','Longitude_rad']].to_numpy())*6371,  columns=df2.Name.unique(), index=df2.Name.unique())
    return distance_similarity_df2

In [30]:
test_distance_matrix = getDistanceMatrix(df2)

In [31]:
def getUserDistCorrelation(distance_matrix, name):
    df2_user=distance_matrix.loc[name,:]
    df2_scaled_user = 1-MinMaxScaler().fit_transform(pd.DataFrame(df2_user))
    return df2_scaled_user

In [32]:
test_user_distance = getUserDistCorrelation(test_distance_matrix, 'Amoli Veer')

In [33]:
def getFinalRecommendatonMatrix(Rec1, Rec2 , name):
    df_recommedation = pd.DataFrame(Rec1)
    df_recommedation['Haversine'] = Rec2
    df_recommedation.rename(columns = {name:'Cosine Similarity'}, inplace = True)
    return df_recommedation

In [34]:
test_final_rec = getFinalRecommendatonMatrix(test_user_corr,test_user_distance,'Amoli Veer' )

NameError: name 'test_user_corr' is not defined

In [36]:
def prioritySetter(df_recommedation,df, priority1, priority2):
    df_recommedation['Score'] = priority1* df_recommedation['Cosine Similarity'] + priority2* df_recommedation['Haversine']
    Hybrid_Recommendation=df_recommedation.sort_values(['Score'], ascending=False)
    Hybrid_rec = Hybrid_Recommendation.index.to_list()
    final_rec = df.set_index('Name').loc[Hybrid_rec[:]].reset_index(inplace=False)
    return final_rec

In [ ]:
prioritySetter(test_final_rec, df, 0.9,0.1)

In [122]:
Name_list = df.Name.to_list()
name_list = widgets.Dropdown(
    options=Name_list,
    description='Names:',
)
Priority1_slider = widgets.FloatSlider(
    value=0.5,
    min=0,
    max=1.0,
    step=0.01,
    description='Personality Priority:',
    disabled=False,
    continuous_update=False,
    orientation='horizontal',
    readout=True,
    readout_format='.2f',
)

display(name_list,Priority1_slider)
button = widgets.Button(
    description='Run',
    disabled=False,
    button_style='success', # 'success', 'info', 'warning', 'danger' or ''
    tooltip='Click me',
    icon='check' # (FontAwesome names without the `fa-` prefix)
    
#     value=0
)
display(button)

def on_button_clicked(b):
    name = name_list.value
    priority1 = Priority1_slider.value
    priority2 = 1- priority1
    print('Personality Priority: {} Percent & Location Priority: {} Percent are set!'.format(priority1*100, priority2*100))

    df1,df2 = get_both_datasets_for_normalisation(df)
    names = ['Flexibility','Composition Percentage','Pincode', 'Interactiveness', 'like_to_be_mentored', 'like_to_mentor', 'Height_in_cms', 'Age']
    df1 = get_df1_normalised(df1,names)
    df1_scaled = df1.copy()
    df1_similarity= getSimilarityMatrix(df1_scaled)
    user_corr = getUserCorrelation(df1_similarity, name)
    df2 = addLatLongRad(df2)
    distance_matrix = getDistanceMatrix(df2)
    user_distance = getUserDistCorrelation(test_distance_matrix, name)
    final_rec = getFinalRecommendatonMatrix(user_corr,user_distance,name)
    Recommendations= prioritySetter(final_rec, df, priority1,priority2)
    display(Recommendations.head(10))

button.on_click(on_button_clicked)

Dropdown(description='Names:', options=('Amoli Veer', 'Kaia Subramanian', 'Rushil Vish', 'Atiksh Manohar', 'Ve…

FloatSlider(value=0.5, continuous_update=False, description='Personality Priority:', max=1.0, step=0.01)

Button(button_style='success', description='Run', icon='check', style=ButtonStyle(), tooltip='Click me')

Personality Priority: 63.0 Percent & Location Priority: 37.0 Percent are set!

,Name,Gender,DOB,Name Of Area,Pincode,Latitude,Longitude,Flexibility,Body Composition,Composition Percentage,Interactiveness,Workout Frequency,Workout Mode Preferred,is_sports_enthusiast,like_to_be_mentored,like_to_mentor,fitness_goal_to_be achieved,addons in session,Height_in_cms,Age
0,Vihaan Mehra,Male,1990-02-13,Airport S.O (Pune),411032,18.57956,73.88954,4,Obese,52,3,Alternate Days,Indoor,No,5,1,All,Meditation,174,31
1,Raunak Jai,Male,1998-10-20,Dhanori B.O,411015,18.58440,73.88738,4,Obese,52,4,Alternate Days,Indoor,No,3,4,All,Meditation,160,22
2,Jay Rastogi,Male,1992-09-07,Ex. Serviceman Colony S.O,411038,18.48029,73.79853,5,Obese,52,1,Alternate Days,Indoor,No,3,1,All,Both,160,28
3,Ishita Mehra,Female,1993-11-06,N.W. College S.O,411001,18.53446,73.88304,5,Obese,56,4,Any Day of Week,Indoor,No,5,1,All,Meditation,161,27
4,Vihaan Dutta,Male,1992-04-29,Pune Weather S.O,411005,18.53245,73.84654,2,Obese,52,3,Any Day of Week,Outdoor,No,5,1,Build muscle,Meditation,177,29
5,Navya Sethi,Female,1986-03-18,Chinchwad East S.O,411019,18.62815,73.83180,5,Obese,56,1,Alternate Days,Indoor,No,4,1,Build muscle,Meditation,164,35
6,Ved Manju,Male,2002-10-22,Rashtra Bhasha Bhavan S.O,411030,18.50942,73.84063,1,Obese,52,5,Any Day of Week,Indoor,No,4,5,All,Meditation,173,18
7,Taarush Meena,Male,1995-11-19,Parvati Gaon S.O,411009,18.49631,73.85621,2,Obese,52,2,Alternate Days,Outdoor,No,4,4,All,Both,170,25
8,Aarav Dhawan,Male,1986-08-22,Kondhwa Lh B.O,411048,18.48028,73.89847,4,Obese,52,3,3 days of week,Indoor,Yes,5,3,Build muscle,Meditation,170,34
9,Ved Lata,Male,1992-07-13,East Khadki S.O,411003,18.55499,73.86108,1,Obese,52,4,Alternate Days,Outdoor,Maybe,2,3,All,Meditation,176,28

In [123]:
df.columns

Index(['Name', 'Gender', 'DOB', 'Name Of Area', 'Pincode', 'Latitude ',
       'Longitude', 'Flexibility', 'Body Composition',
       'Composition Percentage', 'Interactiveness', 'Workout Frequency',
       'Workout Mode Preferred', 'is_sports_enthusiast', 'like_to_be_mentored',
       'like_to_mentor', 'fitness_goal_to_be achieved', 'addons in session',
       'Height_in_cms', 'Age'],
      dtype='object')