In [1]:
import numpy as np
import pandas as pd
import re
import random
from bs4 import BeautifulSoup as bs
import requests
import datetime

In [2]:
np.random.seed(42)

In [3]:
df = pd.read_csv("Final Name - Gender - Location.csv", index_col=[0])

In [4]:
df

,Name,Gender,DOB,Name Of Area,Pincode,Latitude,Longitude
0,Amoli Veer,Female,1982-03-31,Nana Peth S.O,411002,18.51009,73.85672
1,Kaia Subramanian,Female,1994-06-09,Mundhva AV S.O,411036,18.53135,73.91478
2,Rushil Vish,Male,1999-02-07,Yerwada S.O,411006,18.56318,73.87742
3,Atiksh Manohar,Male,1987-07-01,Dapodi S.O,411012,18.57749,73.83138
4,Ved Kapoor,Male,1988-01-28,Hadapsar S.O,411028,18.50453,73.91255
...,...,...,...,...,...,...,...
1382,Neysa Rai,Female,1989-12-10,Mohamadwadi S.O,411060,18.47335,73.90957
1383,Raunak Kapoor,Male,1984-08-12,Masulkar Colony S.O,411018,18.63374,73.81290
1384,Taara Veer,Female,1995-06-06,Masulkar Colony S.O,411018,18.63374,73.81290
1385,Sarthak Rai,Male,1997-09-03,Guruwar Peth S.O,411042,18.50547,73.85951
1386,Kairav Dutta,Male,1999-11-06,Kasarwadi S.O,411034,18.60373,73.82221

In [5]:
df['Flexibility'] = np.random.randint(1, 6, df.shape[0])

In [6]:
df['Flexibility'].value_counts()

1    296
5    284
2    271
4    269
3    267
Name: Flexibility, dtype: int64

In [7]:
df['Body Composition'] = np.random.choice(['Essential Fat', 'Athletes', 'Fitness', 'Acceptable', 'Obese'], df.shape[0])

In [8]:
df['Body Composition']

0       Essential Fat
1             Fitness
2          Acceptable
3            Athletes
4       Essential Fat
            ...
1382          Fitness
1383          Fitness
1384          Fitness
1385          Fitness
1386         Athletes
Name: Body Composition, Length: 1387, dtype: object

## Creating Composition percentage pattern according to compositions https://www.verywellfit.com/what-is-body-composition-3495614#:~:text=Body%20composition%20is%20the%20proportion,muscle%2C%20bones%2C%20and%20organs.

In [ ]:
Description	Women	Men
Essential Fat	10% to 13%	2% to 5%
Athletes	14% to 20%	6% to 13%
Fitness	21% to 24%	14% to 17%
Acceptable	25% to 31%	18% to 24%
Obese	Over 32%	Over 25%

In [17]:
conditions = [
    (df['Gender'] == 'Male') & (df['Body Composition'] == 'Essential Fat'),
    (df['Gender'] == 'Male') & (df['Body Composition'] == 'Athletes'),
    (df['Gender'] == 'Male') & (df['Body Composition'] == 'Fitness'),
    (df['Gender'] == 'Male') & (df['Body Composition'] == 'Acceptable') ,
    (df['Gender'] == 'Male') & (df['Body Composition'] == 'Obese') ,
    (df['Gender'] == 'Female') & (df['Body Composition'] == 'Essential Fat') ,
    (df['Gender'] == 'Female') & (df['Body Composition'] == 'Athletes') ,
    (df['Gender'] == 'Female') & (df['Body Composition'] == 'Fitness') ,
    (df['Gender'] == 'Female') & (df['Body Composition'] == 'Acceptable') ,
    (df['Gender'] == 'Female') & (df['Body Composition'] == 'Obese') ,
    ]



values = [random.randint(2,6), random.randint(6,14), random.randint(14,18),random.randint(18,25), random.randint(25,100),
         random.randint(10,14), random.randint(14,21), random.randint(21,25), random.randint(25,32),random.randint(32,100) ]


df['Composition Percentage'] = np.select(conditions, values)

df.head()

,Name,Gender,DOB,Name Of Area,Pincode,Latitude,Longitude,Flexibility,Body Composition,Composition Percentage
0,Amoli Veer,Female,1982-03-31,Nana Peth S.O,411002,18.51009,73.85672,4,Essential Fat,12
1,Kaia Subramanian,Female,1994-06-09,Mundhva AV S.O,411036,18.53135,73.91478,5,Fitness,22
2,Rushil Vish,Male,1999-02-07,Yerwada S.O,411006,18.56318,73.87742,3,Acceptable,25
3,Atiksh Manohar,Male,1987-07-01,Dapodi S.O,411012,18.57749,73.83138,5,Athletes,12
4,Ved Kapoor,Male,1988-01-28,Hadapsar S.O,411028,18.50453,73.91255,5,Essential Fat,3